name: project_2
description: "A new Flutter Project for MyCIHE"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Core (required for all Firebase services)
  firebase_core: ^2.27.0

  # Firebase Authentication
  firebase_auth: ^4.17.4

  # Cloud Firestore Database
  cloud_firestore: ^4.14.0

  # Firebase Cloud Messaging (for push notifications)
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
